config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'quizzes/new'

  get 'games/new'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  get  '/scoreboard', to: 'static_pages#leaderboard'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'play(/:id)', to: 'games#play', as: :play
  post 'state_update/', to: 'games#state_update', as: :state_update
  get 'show_leaderboard/:id/:row_id', to: 'games#show_leaderboard', as: :leaderboard
  get 'quizzes/show/:id/', to: 'quizzes#show_all_quizzes', as: :show_all_quizzes
  get 'subcategories/show/:id', to: 'subcategories#show_all_subcategories', as: :show_all_subcategories
  get 'users/show_past_history', to: 'users#show_past_history', as: :show_past_history
  get 'games/show_correct', to: 'games#show_correct', as: :show_correct
  get 'auth/:provider/callback', to: 'sessions#extauth'
  get 'auth/google_oauth2', as: :auth_google
  get 'auth/failure', to: 'static_pages#home'
  post 'play/show_correct_options', to: 'games#show_two_options', as: :show_two_options
  post 'play/audience_poll', to: 'games#audience_poll', as: :audience_poll
  resources :users
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :categories,    only: [:create, :new, :index, :destroy, :edit, :update]
  resources :subcategories, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :quizzes,       only: [:create, :new, :index, :destroy, :edit, :update]
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :quizzes, dependent: :destroy
  has_many :scores, dependent: :destroy
  validates :category_id, presence: true
  validates :name,  presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }
  belongs_to :category
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create]
  before_action :admin_user,     only: [:destroy, :new, :create, :update, :edit]

  def new
    @subcategory = Subcategory.new
    @categories = Category.all
  end

  def create
    @subcategory = Subcategory.new(subcategories_params)
    if @subcategory.save
      flash[:success] = "Congratulations. You have created a new subcategory!!"
      redirect_to subcategories_url
    else
      render 'new'
    end
  end

  def index
    @subcategories = Subcategory.all
  end

  def edit
    @subcategory = Subcategory.find(params[:id])
    @categories = Category.all
  end

  def update
    @subcategory = Subcategory.find(params[:id])
    if @subcategory.update_attributes(subcategories_params)
      flash[:success] = "Subcategory updated successfully"
      redirect_to subcategories_path
    else
      render 'edit'
    end
  end

  def destroy
    Subcategory.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  def show_all_subcategories
    category_id = params[:id]
    @subcategories = Subcategory.where(category_id: category_id)
  end

  private
    def subcategories_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/edit.html.erb
<% provide(:title, 'Edit Subcategory') %>
<h1 class="text-center">Edit Subcategory</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @subcategory, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/subcategory_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :category_id, class: 'control-label' %>
        <select name="subcategory[category_id]" id="subcategory_category_id" class="form-control">
          <% @categories.each do |category| %>
            <option value="<%= category.id %>">
              <%= category.name %>
            </option>
          <% end %>
        </select>
        <br>
        <%= f.submit "Edit subcategory", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/subcategories/index.html.erb
<% provide(:title, 'All Subcategories') %>
<h1 class="text-center">All Subcategories</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Subcategory Name</th>
    <th>Quizzes</th>
    <th>Leader Board</th>
    <% if current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	 subcategory.name %></td>
        <td><%=	 link_to "Quizzes", show_all_quizzes_path(subcategory.id) %></td>
        <td><%=	link_to "Leader Board", leaderboard_path(2, subcategory.id) %></td>
        <% if current_user.admin? %>
            <td><%= link_to "Edit", edit_subcategory_path(subcategory.id) %></td>
            <td><%=	 link_to "Delete", subcategory, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>

app/views/subcategories/new.html.erb
<% provide(:title, 'Create Subcategory') %>
<h1 class="text-center">Create Subcategory</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @subcategory, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/subcategory_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :category_id, class: 'control-label' %>
        <select name="subcategory[category_id]" id="subcategory_category_id" class="form-control">
          <% @categories.each do |category| %>
            <option value="<%= category.id %>">
              <%= category.name %>
            </option>
          <% end %>
        </select>
        <br>
        <%= f.submit "Create subcategory", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/subcategories/show_all_subcategories.html.erb
<% provide(:title, 'Subcategories') %>
<h1 class="text-center">Subcategories</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Subcategory Name</th>
    <th>Quizzes</th>
    <% if current_user.admin? %>
        <th>Delete</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	 subcategory.name %></td>
        <td><%=	 link_to "Quizzes", show_all_quizzes_path(subcategory.id) %></td>
        <% if current_user.admin? %>
            <td><%=	 link_to "Delete", subcategory, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>