config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'quizzes/new'

  get 'games/new'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  get  '/scoreboard', to: 'static_pages#leaderboard'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'play(/:id)', to: 'games#play', as: :play
  post 'state_update/', to: 'games#state_update', as: :state_update
  get 'show_leaderboard/:id/:row_id', to: 'games#show_leaderboard', as: :leaderboard
  get 'quizzes/show/:id/', to: 'quizzes#show_all_quizzes', as: :show_all_quizzes
  get 'subcategories/show/:id', to: 'subcategories#show_all_subcategories', as: :show_all_subcategories
  get 'users/show_past_history', to: 'users#show_past_history', as: :show_past_history
  get 'games/show_correct', to: 'games#show_correct', as: :show_correct
  get 'auth/:provider/callback', to: 'sessions#extauth'
  get 'auth/google_oauth2', as: :auth_google
  get 'auth/failure', to: 'static_pages#home'
  post 'play/show_correct_options', to: 'games#show_two_options', as: :show_two_options
  post 'play/audience_poll', to: 'games#audience_poll', as: :audience_poll
  resources :users
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :categories,    only: [:create, :new, :index, :destroy, :edit, :update]
  resources :subcategories, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :quizzes,       only: [:create, :new, :index, :destroy, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'

  has_many  :scores, dependent: :destroy
  has_many  :states, dependent: :destroy
  has_many  :q_states, dependent: :destroy
  has_many  :lifelines, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.password = SecureRandom.urlsafe_base64(10)
      user.email = auth.info.email
      user.gender = auth.info.gender
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_out_user,only: [:new, :create]
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :show]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :index]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @scores = Score.where(is_quiz: true, user_id: params[:id])
  end

  def index
    @users = User.all
    @quizzes = Quiz.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome, #{@user.name}. Nice to see you back on QuizIt"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def show_past_history
    @scores = Score.where(user_id: current_user.id)
    @quizzes = Quiz.all
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}.png?d=monsterid&s=#{size}"
    image_tag(gravatar_url, alt: user.name, :class => "text-center")
  end

  def show_score(user)
    score = Score.where(user_id: user.id, is_quiz: true)
    score_sum = score.sum(:total)
    score_count = score.count
    if score_count == 0
      @rating = "Unrated"
    else
      @rating = score_sum/score_count
    end
  end

end

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<h1 class="text-center">Update Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>

        <%= f.label :email, class: 'control-label' %>
        <%= f.email_field :email, class: 'form-control' %>
        <br>

        <%= f.label :password, class: 'control-label' %>
        <%= f.password_field :password, class: 'form-control' %>
        <br>

        <%= f.label :password_confirmation, "Confirmation", class: 'control-label' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <br>

        <%= f.label :gender, class: 'control-label' %>
        <%=	f.select :gender, options_for_select([["Male", "Male"], ["Female", "Female"]]), {}, {:class => 'form-control'} %>
        <br>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 class="text-center">All Users</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Profile Picture</th>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>View</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @users.each do |user| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	 gravatar_for user, size: 60 %></td>
        <td><%=	 user.name %></td>
        <td><%=	 user.email %></td>
        <td><%=	 user.gender %></td>
        <td><%=	 link_to "View Profile", user %></td>
        <% if !(current_user == user) %>
            <td><%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% else %>
            <td><%= link_to "Delete", "#" %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>

        <%= f.label :email, class: 'control-label' %>
        <%= f.email_field :email, class: 'form-control' %>
        <br>

        <%= f.label :password, class: 'control-label' %>
        <%= f.password_field :password, class: 'form-control' %>
        <br>

        <%= f.label :password_confirmation, "Confirmation", class: 'control-label' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <br>

        <%= f.label :gender, class: 'control-label' %>
        <%=	f.select :gender, options_for_select([["Male", "Male"], ["Female", "Female"]]), {}, {:class => 'form-control'} %>

        <br>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="card">
        <%= image_tag("https://www.gravatar.com/avatar/#{Digest::MD5::hexdigest(@user.email.downcase)}.png?d=monsterid&s=300",
                      alt: @user.name, :style => "width: 100%;") %>
        <h1><%= @user.name %></h1>
        <p class="title">
          <%= @user.email %>
        </p>
        <p class="title">
          Rating: <%= show_score @user %>
        </p>
        <p><%= @user.gender %></p>
      </div>
    </div>
    <div class="col-sm-9">
      <table class="table table-striped table-hover ">
        <thead>
        <tr>
          <th>#</th>
          <th>Quiz Name</th>
          <th>Subcategory Name</th>
          <th>Category Name</th>
          <% if current_user == @user %>
            <th>Play Again</th>
          <% end %>
          <th>Max Score</th>
        </tr>
        </thead>
        <tbody>
        <%= ctr = 0 %>
        <% @scores.each do |score| %>
            <tr>
              <td><%= ctr + 1 %></td>
              <p hidden><%= quiz = Quiz.find(score.quiz_id) %></p>
              <td><%=	quiz.name %></td>
              <td><%=	quiz.subcategory.name %></td>
              <td><%=	quiz.subcategory.category.name %></td>
              <% if current_user == @user %>
                  <td><%=	link_to "Play Again", play_path(score.quiz_id) %></td>
              <% end %>
              <td><%=	score.total %></td>
            </tr>
            <%=	 ctr = ctr + 1 %>
            <% if ctr == 10 %>
              <% break %>
            <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="hero-widget well well-sm">
        <div class="icon">
          <i class="glyphicon glyphicon-th-list"></i>
        </div>
        <div class="text">
          <label class="text-muted">Categories</label>
        </div>
        <div class="options">
          <%= link_to categories_path, class: "btn btn-primary btn-lg" do %>
              <i class='glyphicon glyphicon-plus'></i> Categories
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="hero-widget well well-sm">
        <div class="icon">
          <i class="glyphicon glyphicon-list"></i>
        </div>
        <div class="text">
          <label class="text-muted">Subcategories</label>
        </div>
        <div class="options">
          <%= link_to subcategories_path, class: "btn btn-primary btn-lg" do %>
              <i class='glyphicon glyphicon-plus'></i> Subcategories
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="hero-widget well well-sm">
        <div class="icon">
          <i class="glyphicon glyphicon-list-alt"></i>
        </div>
        <div class="text">
          <label class="text-muted">Quizzes</label>
        </div>
        <div class="options">
          <%= link_to quizzes_path, class: "btn btn-primary btn-lg" do %>
              <i class='glyphicon glyphicon-plus'></i> Quizzes
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="hero-widget well well-sm">
        <div class="icon">
          <i class="glyphicon glyphicon-signal"></i>
        </div>
        <div class="text">
          <label class="text-muted">Leaderboard</label>
        </div>
        <div class="options">
          <%= link_to scoreboard_path, class: "btn btn-primary btn-lg" do %>
              <i class='glyphicon glyphicon-plus'></i> Leaderboard
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if current_user.admin? %>
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <div class="hero-widget well well-sm">
            <div class="icon">
              <i class="glyphicon glyphicon-log-in"></i>
            </div>
            <div class="text">
              <label class="text-muted">Create Category</label>
            </div>
            <div class="options">
              <%= link_to new_category_path, class: "btn btn-primary btn-lg" do %>
                  <i class='glyphicon glyphicon-plus'></i> Category
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="hero-widget well well-sm">
            <div class="icon">
              <i class="glyphicon glyphicon-new-window"></i>
            </div>
            <div class="text">
              <label class="text-muted">Create Subcategories</label>
            </div>
            <div class="options">
              <%= link_to new_subcategory_path, class: "btn btn-primary btn-lg" do %>
                  <i class='glyphicon glyphicon-plus'></i> Subcategories
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="hero-widget well well-sm">
            <div class="icon">
              <i class="glyphicon glyphicon-circle-arrow-right"></i>
            </div>
            <div class="text">
              <label class="text-muted">Create Quizzes</label>
            </div>
            <div class="options">
              <%= link_to new_quiz_path, class: "btn btn-primary btn-lg" do %>
                  <i class='glyphicon glyphicon-plus'></i> Quizzes
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="hero-widget well well-sm">
            <div class="icon">
              <i class="glyphicon glyphicon-tasks"></i>
            </div>
            <div class="text">
              <label class="text-muted">View All Users</label>
            </div>
            <div class="options">
              <%= link_to users_path, class: "btn btn-primary btn-lg" do %>
                  <i class='glyphicon glyphicon-plus'></i> Users
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/show_past_history.html.erb
<% provide(:title, "Past Submissions") %>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Quiz Name</th>
    <th>Subcategory Name</th>
    <th>Category Name</th>
    <th>Play Again</th>
    <th>Attempted?</th>
    <th>Max Score</th>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @quizzes.each do |quiz| %>
    <tr>
      <td><%= ctr + 1 %></td>
      <p hidden><%= score = Score.find_by(user_id: current_user.id, quiz_id: quiz.id) %></p>
      <td><%=	quiz.name %></td>
      <td><%=	quiz.subcategory.name %></td>
      <td><%=	quiz.subcategory.category.name %></td>
      <% if score %>
          <td><%=	link_to "Play Again", play_path(quiz.id) %></td>
          <td>Attempted</td>
          <td><%=	score.total %></td>
      <% else %>
          <td><%=	link_to "Play Game", play_path(quiz.id) %></td>
          <td>Not Attempted</td>
          <td>0</td>
      <% end %>
      <%=	 ctr = ctr + 1 %>
    </tr>
  <% end %>
  </tbody>
</table>