config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'quizzes/new'

  get 'games/new'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  get  '/scoreboard', to: 'static_pages#leaderboard'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'play(/:id)', to: 'games#play', as: :play
  post 'state_update/', to: 'games#state_update', as: :state_update
  get 'show_leaderboard/:id/:row_id', to: 'games#show_leaderboard', as: :leaderboard
  get 'quizzes/show/:id/', to: 'quizzes#show_all_quizzes', as: :show_all_quizzes
  get 'subcategories/show/:id', to: 'subcategories#show_all_subcategories', as: :show_all_subcategories
  get 'users/show_past_history', to: 'users#show_past_history', as: :show_past_history
  get 'games/show_correct', to: 'games#show_correct', as: :show_correct
  get 'auth/:provider/callback', to: 'sessions#extauth'
  get 'auth/google_oauth2', as: :auth_google
  get 'auth/failure', to: 'static_pages#home'
  post 'play/show_correct_options', to: 'games#show_two_options', as: :show_two_options
  post 'play/audience_poll', to: 'games#audience_poll', as: :audience_poll
  resources :users
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :categories,    only: [:create, :new, :index, :destroy, :edit, :update]
  resources :subcategories, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :quizzes,       only: [:create, :new, :index, :destroy, :edit, :update]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many  :subcategories, dependent: :destroy
  has_many  :scores, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :admin_user,     only: [:destroy, :new, :create, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = "Congratulations. You have created a new category!!"
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(categories_params)
      flash[:success] = "Category updated successfully"
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  private
    def categories_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category') %>
<h1 class="text-center">Edit Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @category, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/category_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>

        <%= f.submit "Edit category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, 'All Categories') %>
<h1 class="text-center">All Categories</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Category Name</th>
    <th>Subcategories</th>
    <th>Leader Board</th>
    <% if current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @categories.each do |category| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	category.name %></td>
        <td><%=	link_to "Subcategories", show_all_subcategories_path(category.id) %></td>
        <td><%=	link_to "Leader Board", leaderboard_path(1, category.id) %></td>
        <% if current_user.admin? %>
            <td><%= link_to "Edit", edit_category_path(category.id) %></td>
            <td><%=	 link_to "Delete", category, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<% provide(:title, 'Create Category') %>
<h1 class="text-center">Create Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @category, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/category_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>

        <%= f.submit "Create category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>