config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'quizzes/new'

  get 'games/new'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  get  '/scoreboard', to: 'static_pages#leaderboard'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'play(/:id)', to: 'games#play', as: :play
  post 'state_update/', to: 'games#state_update', as: :state_update
  get 'show_leaderboard/:id/:row_id', to: 'games#show_leaderboard', as: :leaderboard
  get 'quizzes/show/:id/', to: 'quizzes#show_all_quizzes', as: :show_all_quizzes
  get 'subcategories/show/:id', to: 'subcategories#show_all_subcategories', as: :show_all_subcategories
  get 'users/show_past_history', to: 'users#show_past_history', as: :show_past_history
  get 'games/show_correct', to: 'games#show_correct', as: :show_correct
  get 'auth/:provider/callback', to: 'sessions#extauth'
  get 'auth/google_oauth2', as: :auth_google
  get 'auth/failure', to: 'static_pages#home'
  post 'play/show_correct_options', to: 'games#show_two_options', as: :show_two_options
  post 'play/audience_poll', to: 'games#audience_poll', as: :audience_poll
  resources :users
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :categories,    only: [:create, :new, :index, :destroy, :edit, :update]
  resources :subcategories, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :quizzes,       only: [:create, :new, :index, :destroy, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | QuizIt</title>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=	stylesheet_link_tag "bootswatch" %>
    <%=	stylesheet_link_tag "base" %>
    <%= stylesheet_link_tag "another" %>
    <%= stylesheet_link_tag "leaderboard" %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=	 link_to "QuizIt", home_path, id: "logo", class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <% if logged_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li><%= link_to "Past Submissions", show_past_history_path %></li>
                    <% if current_user.admin? %>
                        <li><%= link_to "Questions", questions_path %></li>
                    <% end %>
                    <li class="divider"></li>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                  </ul>
                </li>
                <li><a href="#"><i class="fa fa-user"></i>  Hi,  <%=	 @current_user.name %>!</a></li>
            <% else %>
                <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="margin: 0 auto;">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-dismissible alert-<%= message_type %>">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
      <% end %>
      <%= yield %>
    </div>
    <br>
    <br>
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-inline">
              <li><%= link_to "Home", home_path %></li>
              <li class="footer-menu-divider"></li>
              <li><%= link_to "About", about_path %></li>
              <li class="footer-menu-divider"></li>
              <% if logged_in? %>
                  <li><%= link_to "logout", logout_path %></li>
              <% else %>
                  <li><%= link_to "login", login_path %></li>
                  <li class="footer-menu-divider"></li>
                  <li><%= link_to "Register", signup_path %></li>
              <% end %>
              <li class="footer-menu-divider"></li>
            </ul>
            <p class="copyright text-muted small">Copyright © 2017. All Rights Reserved</p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>